// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEW5TBHa7lfyHBL2VrWmWjwiU-XxuCZBY',
    appId: '1:768854430451:web:f245f2091076d001cc5d86',
    messagingSenderId: '768854430451',
    projectId: 'halochat-e2325',
    authDomain: 'halochat-e2325.firebaseapp.com',
    storageBucket: 'halochat-e2325.appspot.com',
    measurementId: 'G-ZFW418LWP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaSqqWa61jW7OMJ9R5S6nZXu7jRxsZRTc',
    appId: '1:768854430451:android:251f0a4ee6f0a0a1cc5d86',
    messagingSenderId: '768854430451',
    projectId: 'halochat-e2325',
    storageBucket: 'halochat-e2325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCpBxgdie2R18LRunUhlZ1u1bt1ma5TE0',
    appId: '1:768854430451:ios:b23e7fd3907603b6cc5d86',
    messagingSenderId: '768854430451',
    projectId: 'halochat-e2325',
    storageBucket: 'halochat-e2325.appspot.com',
    iosClientId: '768854430451-43nj4rq1drm4ip917ifa7f1jgo6o2e4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.haloChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCpBxgdie2R18LRunUhlZ1u1bt1ma5TE0',
    appId: '1:768854430451:ios:b23e7fd3907603b6cc5d86',
    messagingSenderId: '768854430451',
    projectId: 'halochat-e2325',
    storageBucket: 'halochat-e2325.appspot.com',
    iosClientId: '768854430451-43nj4rq1drm4ip917ifa7f1jgo6o2e4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.haloChat',
  );
}
